### ISSUE TITLE
没有兼容 py2.7

### ISSUE THREAD

**Issue by Samurais** [hankcs/pyhanlp#1]
使用py2.7, pip 9.0.1 进行测试，报错：

```
Collecting pyhanlp
  Downloading pyhanlp-0.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/m8/qbdvflrd3312_r3sxyc19k9r0000gn/T/pip-build-Yp9Etm/pyhanlp/setup.py", line 10, in <module>
        with open(join(this_dir, 'README.md'), encoding='utf-8') as file:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/m8/qbdvflrd3312_r3sxyc19k9r0000gn/T/pip-build-Yp9Etm/pyhanlp/
(venv-py2)
```

**Comment by hankcs** [comment]
我不常用Python2，不过欢迎参与移植！

**Comment by Samurais** [comment]
#2 帮忙review，感谢！

@hankcs
