### ISSUE TITLE
hanlp serve ImportError: cannot import name 'ENVIRON'

### ISSUE THREAD

**Issue by vainl** [hankcs/pyhanlp#18]
`OS: CentOS Linux release 7.4.1708 (Core)`
```
$ hanlp  -v
jar  1.6.3: /usr/lib/python3.6/site-packages/pyhanlp/static/hanlp-1.6.3.jar
data 1.6.2:  #/usr/lib/python3.6/site-packages/pyhanlp/static/data
config    : /usr/lib/python3.6/site-packages/pyhanlp/static/hanlp.properties
```

```
$ hanlp serve
Traceback (most recent call last):
  File "/usr/bin/hanlp", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/pyhanlp/main.py", line 101, in main
    from pyhanlp import server
  File "/usr/lib/python3.6/site-packages/pyhanlp/server.py", line 23, in <module>
    from pyhanlp import HanLP, ENVIRON, PerceptronLexicalAnalyzer
ImportError: cannot import name 'ENVIRON'
```

**Comment by hankcs** [comment]
Merged, thanks.
