### ISSUE TITLE
HanLP.Config 显示HanLP没有Config属性

### ISSUE THREAD

**Issue by wancong** [hankcs/pyhanlp#23]
首先感谢hankcs提供这么好用的包！ 新手学习中：）

环境： ubuntu 16.04
输入：
>>> from pyhanlp import *
>>> HanLP.Config

输出：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wancong/.local/lib/python3.5/site-packages/pyhanlp/__init__.py", line 137, in __getattr__
    return getattr(self._proxy, attr)
AttributeError: type object 'com.hankcs.hanlp.HanLP' has no attribute 'Config'

个人思考：
java中，Config是static final，是常量，运行过程中不可更改。请问是否是这个原因呢？
如果我想在python中实现这样的效果:
HanLP.Config.ShowTermNature = False  #关闭词性显示
请问该怎么做呢？

**Comment by hankcs** [comment]
请参考：https://github.com/hankcs/pyhanlp/blob/master/pyhanlp/main.py#L89

**Comment by wancong** [comment]
感谢！！秒回啊
