### ISSUE TITLE
分类200个报错

### ISSUE THREAD

**Issue by zy486at189cn** [hankcs/pyhanlp#33]
@hankcs @vainl @wancong @Samurais 
当我使用demo_text_classification.py分类195类的文档，每类文档小于110个样本，每个样本文字小于2000字，训练时报错如下：
耗时 9370 ms 加载了 195 个类目,共 16762 篇文档
原始数据集大小:16762
使用卡方检测选择特征中...耗时 315 ms,选中特征数:72677 / 74521 = 97.53%
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    classifier = train_or_load_classifier()
  File "train.py", line 18, in train_or_load_classifier
    classifier.train(corpus_path)
jpype._jexception.OutOfMemoryErrorPyRaisable: java.lang.OutOfMemoryError: GC overhead limit exceeded
这个问题如何解决？谢谢！

**Comment by hankcs** [comment]
用FileDataSet：https://github.com/hankcs/HanLP/wiki/%E6%96%87%E6%9C%AC%E5%88%86%E7%B1%BB%E4%B8%8E%E6%83%85%E6%84%9F%E5%88%86%E6%9E%90#%E6%95%B0%E6%8D%AE%E9%9B%86%E5%AE%9E%E7%8E%B0

**Comment by zy486at189cn** [comment]
@hankcs 我的程序用了文件子目录，程序如下：
# -*- coding:utf-8 -*-
# Author：hankcs
# Date: 2018-05-23 17:26
import os
from pyhanlp import SafeJClass
from tests.test_utility import ensure_data

NaiveBayesClassifier = SafeJClass('com.hankcs.hanlp.classification.classifiers.NaiveBayesClassifier')
IOUtil = SafeJClass('com.hankcs.hanlp.corpus.io.IOUtil')

def train_or_load_classifier():
    corpus_path = 'data'
    model_path = corpus_path + '.pb'
    classifier = NaiveBayesClassifier()
    classifier.train(corpus_path)
    model = classifier.getModel()
    IOUtil.saveObjectTo(model, model_path)

if __name__ == '__main__':
    classifier = train_or_load_classifier()

其中data目录下就是训练文件，程序如何修改？盼告知，谢谢！

**Comment by clnFind** [comment]
![image](https://user-images.githubusercontent.com/14065604/41964372-5d03a8ca-7a2c-11e8-84b4-9af01912b845.png)

```
    corpus_path = "/home/THUCNews"
    fileset = Fileset(corpus_path)
    if os.path.isfile(model_path):
        return NaiveBayesClassifier(IOUtil.readObjectFrom(model_path))
    classifier = NaiveBayesClassifier()
    classifier.train(fileset)
    model = classifier.getModel()
    IOUtil.saveObjectTo(model, model_path)
```
垃圾桶回收超限，想问下作者提到的，python怎么调用FileDataSet，处理这个问题？？？谢谢🙏
