### ISSUE TITLE
JClass 方式调用 TextRankKeyword 方法失败

### ISSUE THREAD

**Issue by zxygentoo** [hankcs/pyhanlp#39]
似乎只有 KeywordList 是可以成功的，其他几个都会报 No matching overloads 的错误

```
Python 3.6.5 (default, Apr 18 2018, 14:32:25) 
>>> text = "程序员(英文Programmer)是从事程序开发、维护的专业人员。"
>>> TRK = JClass('com.hankcs.hanlp.summary.TextRankKeyword')
>>> 
>>> TRK.getKeywordList(text, 3)
<jpype._jclass.java.util.ArrayList object at 0x7f965808f0b8>
>>> TRK.getKeyword(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: No matching overloads found for getKeyword in find. at native/common/jp_method.cpp:127
>>> TRK.getTermAndRank(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: No matching overloads found for getTermAndRank in find. at native/common/jp_method.cpp:127
>>> TRK.getTermAndRank(text, 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: No matching overloads found for getTermAndRank in find. at native/common/jp_method.cpp:127
```

我尝试过去构造一个 Term List 调用 getRank，也会失败，不过我不太确定构造方法是不是有问题。但以上两个按说参数都是简单的字符串和整数，jpype 应该是可以做正确转换的。然后查看了 jpype 的文档和搜索了网络也没发现太有价值的参考。

有没有什么建议？谢谢～

**Comment by hankcs** [comment]
Hi，这些方法是非static的，必须创建对象：

```
text = "程序员(英文Programmer)是从事程序开发、维护的专业人员。"
TRK = JClass('com.hankcs.hanlp.summary.TextRankKeyword')()
print(TRK.getKeyword(text))
```

**Comment by zxygentoo** [comment]
明白了，多谢🙏
