### ISSUE TITLE
[Contribution] 尝试支持自定义 STATIC_ROOT 时 Java 部分实现报错

### ISSUE THREAD

**Issue by huntzhan** [hankcs/pyhanlp#41]
Hi Hankcs （sorry 我不知道如何称呼您）,

由于个人需求，我想要在 `pyhanlp` 里加入自定义 `STATIC_ROOT` 路径的支持，目的是可以自定义 jar & data 路径，方便 build docker image 以及其他应用场景的应用。具体的做法是，加入一个 `HANLP_STATIC_ROOT` 环境变量，如果不存在则走当前的逻辑。

但是，经过一番尝试后，我发现这个改动还会依赖于 Hanlp 实现，所以想要咨询一下如何写是正确的。目前 `hanlp_installed_jar_versions` 会返回为 `not None`，然后进入 java 实现部分报错。改完之后我会提一个 PR，以方便其他与我有同样需求的用户。

我做的尝试 （已经 export `HANLP_STATIC_ROOT` 指向自定义路径，但 java 实现还是会引用 static folder 的路径）：
https://github.com/huntzhan/pyhanlp/commit/dbdcb270b9a7669eaa6c9078230d4122b2a4b106

跑 test 的报错：

```
(py365--yHyR577) ➜  pyhanlp python tests/test_hanlp.py

I0702 02:27:03.275280 140736315225024 test_hanlp.py:56] test_analyze
Jul 02, 2018 2:27:03 AM com.hankcs.hanlp.corpus.io.ByteArrayFileStream createByteArrayFileStream
WARNING: java.io.FileNotFoundException: /Users/haoxun/Data/Project/pyhanlp/pyhanlp/static/data/model/perceptron/pku199801/cws.bin (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.hankcs.hanlp.corpus.io.ByteArrayFileStream.createByteArrayFileStream(ByteArrayFileStream.java:39)
	at com.hankcs.hanlp.corpus.io.ByteArrayStream.createByteArrayStream(ByteArrayStream.java:38)
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.load(LinearModel.java:371)
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.<init>(LinearModel.java:64)
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.<init>(PerceptronLexicalAnalyzer.java:55)
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.<init>(PerceptronLexicalAnalyzer.java:80)

EI0702 02:27:03.405775 140736315225024 test_hanlp.py:91] test_custom_dict
Jul 02, 2018 2:27:03 AM com.hankcs.hanlp.corpus.io.IOUtil readBytes
WARNING: 读取/Users/haoxun/Data/Project/pyhanlp/pyhanlp/static/data/dictionary/CoreNatureDictionary.txt.bin时发生异常java.io.FileNotFoundException: /Users/haoxun/Data/Project/pyhanlp/pyhanlp/static/data/dictionary/CoreNatureDictionary.txt.bin (No such file or directory)
Jul 02, 2018 2:27:03 AM com.hankcs.hanlp.dictionary.CoreDictionary load
WARNING: 核心词典/Users/haoxun/Data/Project/pyhanlp/pyhanlp/static/data/dictionary/CoreNatureDictionary.txt不存在！java.io.FileNotFoundException: /Users/haoxun/Data/Project/pyhanlp/pyhanlp/static/data/dictionary/CoreNatureDictionary.txt (No such file or directory)
EI0702 02:27:03.439275 140736315225024 test_hanlp.py:39] test_keywords
EI0702 02:27:03.443824 140736315225024 test_hanlp.py:50] test_parsedependency
Jul 02, 2018 2:27:03 AM com.hankcs.hanlp.corpus.io.ByteArrayFileStream createByteArrayFileStream
WARNING: java.io.FileNotFoundException: /Users/haoxun/Data/Project/pyhanlp/pyhanlp/static/data/model/dependency/NNParserModel.txt.bin (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.hankcs.hanlp.corpus.io.ByteArrayFileStream.createByteArrayFileStream(ByteArrayFileStream.java:39)
	at com.hankcs.hanlp.corpus.io.ByteArrayStream.createByteArrayStream(ByteArrayStream.java:38)
	at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkParser.load(NeuralNetworkParser.java:132)
	at com.hankcs.hanlp.dependency.nnparser.parser_dll.<init>(parser_dll.java:42)
	at com.hankcs.hanlp.dependency.nnparser.parser_dll.<init>(parser_dll.java:32)
	at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkDependencyParser.<init>(NeuralNetworkDependencyParser.java:39)
	at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkDependencyParser.compute(NeuralNetworkDependencyParser.java:94)
	at com.hankcs.hanlp.HanLP.parseDependency(HanLP.java:708)

Jul 02, 2018 2:27:03 AM com.hankcs.hanlp.corpus.io.IOUtil$LineIterator <init>
WARNING: 文件/Users/haoxun/Data/Project/pyhanlp/pyhanlp/static/data/model/dependency/NNParserModel.txt不存在，接下来的调用会返回null
java.io.FileNotFoundException: /Users/haoxun/Data/Project/pyhanlp/pyhanlp/static/data/model/dependency/NNParserModel.txt (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.hankcs.hanlp.corpus.io.IOUtil.newInputStream(IOUtil.java:625)
	at com.hankcs.hanlp.corpus.io.IOUtil$LineIterator.<init>(IOUtil.java:488)
	at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkParser.loadTxt(NeuralNetworkParser.java:156)
	at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkParser.load(NeuralNetworkParser.java:133)
	at com.hankcs.hanlp.dependency.nnparser.parser_dll.<init>(parser_dll.java:42)
	at com.hankcs.hanlp.dependency.nnparser.parser_dll.<init>(parser_dll.java:32)
	at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkDependencyParser.<init>(NeuralNetworkDependencyParser.java:39)
	at com.hankcs.hanlp.dependency.nnparser.NeuralNetworkDependencyParser.compute(NeuralNetworkDependencyParser.java:94)
	at com.hankcs.hanlp.HanLP.parseDependency(HanLP.java:708)

EI0702 02:27:03.464127 140736315225024 test_hanlp.py:75] test_segment
EI0702 02:27:03.465986 140736315225024 test_hanlp.py:44] test_textsum
E
======================================================================
ERROR: test_analyze (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_hanlp.py", line 57, in test_analyze
    analyzer = PerceptronLexicalAnalyzer()
  File "/Users/haoxun/Data/Project/pyhanlp/pyhanlp/__init__.py", line 143, in __call__
    proxy = self._proxy()
  File "/Users/haoxun/.local/share/virtualenvs/py365--yHyR577/lib/python3.6/site-packages/jpype/_jclass.py", line 111, in _javaInit
    *args)
jpype._jexception.java.io.IOExceptionPyRaisable: java.io.IOException: /Users/haoxun/Data/Project/pyhanlp/pyhanlp/static/data/model/perceptron/pku199801/cws.bin 加载失败

======================================================================
ERROR: test_custom_dict (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_hanlp.py", line 94, in test_custom_dict
    assert len(HanLP.segment(text)) == 12, "添加自定义词汇前，分词结果预期"
jpype._jexception.java.lang.ExceptionInInitializerErrorPyRaisable: java.lang.ExceptionInInitializerError

======================================================================
ERROR: test_keywords (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_hanlp.py", line 41, in test_keywords
    print(HanLP.extractKeyword(self.document, 2))
jpype._jexception.java.lang.NoClassDefFoundErrorPyRaisable: java.lang.NoClassDefFoundError: Could not initialize class com.hankcs.hanlp.dictionary.CoreDictionary

======================================================================
ERROR: test_parsedependency (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_hanlp.py", line 52, in test_parsedependency
    logging.info(HanLP.parseDependency(sentence))
jpype._jexception.java.lang.IllegalArgumentExceptionPyRaisable: java.lang.IllegalArgumentException: 加载神经网络依存句法模型[/Users/haoxun/Data/Project/pyhanlp/pyhanlp/static/data/model/dependency/NNParserModel.txt]失败！

======================================================================
ERROR: test_segment (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_hanlp.py", line 76, in test_segment
    print(HanLP.segment('你好，欢迎在Python中调用HanLP的API'))
jpype._jexception.java.lang.NoClassDefFoundErrorPyRaisable: java.lang.NoClassDefFoundError: Could not initialize class com.hankcs.hanlp.dictionary.CoreDictionary

======================================================================
ERROR: test_textsum (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_hanlp.py", line 46, in test_textsum
    print(HanLP.extractSummary(self.document, 3))
jpype._jexception.java.lang.NoClassDefFoundErrorPyRaisable: java.lang.NoClassDefFoundError: Could not initialize class com.hankcs.hanlp.dictionary.CoreDictionary

----------------------------------------------------------------------
Ran 6 tests in 0.196s

FAILED (errors=6)
```

**Comment by hankcs** [comment]
Hi，感谢反馈。

请参考`pyhanlp/main.py`中的import：

```python
from pyhanlp import HanLP, PATH_CONFIG, HANLP_JAR_VERSION, HANLP_JAR_PATH, HANLP_DATA_PATH, \
    hanlp_installed_data_version, STATIC_ROOT
```

不要import `pyhanlp/static/__init__.py`中的相关变量，一旦import static包，那就一定是从安装目录加载。
